spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${R2DBC_HOST}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
  flyway:
    url: ${FLYWAY_HOST}
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key: ${ACCESS_KEY}
        secret-key: ${SECRET_KEY}
      region:
        static: ${SQS_REGION}

sqs:
  notifications:
    queue:
      name: ${SQS_NAME}
      region: ${SQS_REGION}